//Code generated by go generate; DO NOT EDIT.

export interface Main {
	body: string;
	email: string;
	id: number;
	name: string;
	postId: number;
}
export interface Main {
	body: string;
	id: number;
	title: string;
	userId: number;
}
