//Code generated by go generate; DO NOT EDIT.

export interface Options {
	color: string;
	size: string;
}

export interface Option {
	color: string;
	size: string;
}

export interface Main {
	age: number;
	name: string;
	option: Partial<Option>;
	options: Array<Partial<Options>>;
	price: number;
	sizes: Array<string>;
	startDate: string;
}
